services:
  game-server:
    build: .
    container_name: sketchit
    restart: unless-stopped
    ports:
      - "80:5000" # Connects VPS port 80 to App port 5000
    environment:
      - PYTHONUNBUFFERED=1 # Ensures logs show up in real-time
